import React from 'react';
import {
  IonSlides,
  IonSlide,
  IonContent,
  IonCard,
  IonCardHeader,
  IonCardSubtitle,
  IonCardTitle,
  IonCardContent,
  IonItem,
  IonIcon,
  IonLabel,
} from '@ionic/react';
import {search, wifi, wine, warning, walk} from 'ionicons/icons';
import '../theme/Splash.css';

import {Header} from '../components/Header';

import {restfulAPIPatternsURL,swaggerUIURL} from '../constants';

export const Splash: React.FC = () => (
  <IonContent>
    <Header></Header>
    <IonSlides pager={true}>
      <IonSlide>
        <IonCard>
          <IonCardHeader>
            <IonCardTitle>Welcome to Good Goods.</IonCardTitle>
            <IonCardSubtitle>the web2py marketplace demo</IonCardSubtitle>
          </IonCardHeader>
          <IonCardContent>
            Simply swipe right and learn more about our highlighted features.
          </IonCardContent>
        </IonCard>
      </IonSlide>
      <IonSlide>
        <IonCard>
          <IonCardHeader>
            <IonCardTitle>web2py marketplace demo</IonCardTitle>
            <IonCardSubtitle>Highlighted features</IonCardSubtitle>
          </IonCardHeader>
          <IonItem href={swaggerUIURL} className="ion-activated">
            <IonIcon icon={wifi} slot="start" />
            <IonLabel>pyDAL Database Abstraction Layer</IonLabel>
          </IonItem>
          <IonItem href={restfulAPIPatternsURL} className="ion-activated">
            <IonIcon icon={wifi} slot="start" />
            <IonLabel>web2py Autogenerated RESTful API</IonLabel>
          </IonItem>
          <IonItem href={swaggerUIURL} className="ion-activated">
            <IonIcon icon={wifi} slot="start" />
            <IonLabel>Database Autogenerated Swagger Documentation</IonLabel>
          </IonItem>
          <IonItem href={swaggerUIURL} className="ion-activated">
            <IonIcon icon={wifi} slot="start" />
            <IonLabel>Typescript Swagger Generated API Client</IonLabel>
          </IonItem>
          <IonItem href="#" className="ion-activated">
            <IonIcon icon={search} slot="start" />
            <IonLabel>JSONSchema Forms</IonLabel>
          </IonItem>
          <IonItem href="#" className="ion-activated">
            <IonIcon icon={search} slot="start" />
            <IonLabel>Elasticsearch powered faceted search</IonLabel>
          </IonItem>
          <IonItem href="#" className="ion-activated">
            <IonIcon icon={search} slot="start" />
            <IonLabel>Progressive Web, Android, iOS Apps</IonLabel>
          </IonItem>
          <IonItem href="#" className="ion-activated">
            <IonIcon icon={search} slot="start" />
            <IonLabel>Electron Desktop App</IonLabel>
          </IonItem>
        </IonCard>
      </IonSlide>
      <IonSlide>
        <IonCard>
          <IonCardHeader>
            <IonCardTitle>Steps to use the app.</IonCardTitle>
            <IonCardSubtitle>the web2py marketplace demo</IonCardSubtitle>
          </IonCardHeader>
          <IonItem href="/user/register">
            <IonIcon icon={wine} slot="start" />
            <IonLabel>Register</IonLabel>
          </IonItem>
          <IonItem href="/user/register" className="ion-activated">
            <IonIcon icon={warning} slot="start" />
            <IonLabel>Create Inventory Items</IonLabel>
          </IonItem>
          <IonItem href="/user/register">
            <IonIcon icon={walk} slot="start" />
            <IonLabel>Search Public Inventory</IonLabel>
          </IonItem>
          <IonItem href="/user/register">
            <IonIcon icon={walk} slot="start" />
            <IonLabel>Add to Cart</IonLabel>
          </IonItem>
          <IonItem href="/user/register">
            <IonIcon icon={walk} slot="start" />
            <IonLabel>Create Purchase Order</IonLabel>
          </IonItem>
        </IonCard>
      </IonSlide>
    </IonSlides>
  </IonContent>
);
