version: '2'
services:
  es01:
    user: elasticsearch
    entrypoint:
      - elasticsearch
      - -Ehttp.port=9200
      - -Ehttp.cors.enabled=true
      - -Ehttp.cors.allow-origin=*
      - -Ehttp.cors.allow-headers=Content-Type,Content-Length,Authorization
      - -Ehttp.cors.allow-credentials=true
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic
networks:
  elastic:
    driver: bridge