version: '3'
services:
  swagger-editor:
    container_name: swagger-editor
    image: swaggerapi/swagger-editor:v3.14.8
    restart: unless-stopped
    ports:
      - 0.0.0.0:8080:8080
    volumes:
      - ./api/swagger.json:/swagger.json
    environment:
      SWAGGER_JSON: /swagger.json
    healthcheck:
      test: ["CMD-SHELL", "curl 127.0.0.1:8080/swagger.json"]
      interval: 60s
      timeout: 5s
      retries: 5