export const AppName = 'Good Goods';
export const userTokenKey = 'good_goods_user_token';
export const userIdKey = 'good_goods_user_id';
export const userTokenExpirationKey = 'good_goods_user_token_expiration';
export const userTokenExpirationMinutes = 29;
export const userTokenAllowedDiffMinutes = 5;
export const userIdHeaderKey = 'x-gg-userid';
export const userCartKey = "good_goods_user_cart";

export const apiBaseUrl = 'http://127.0.0.1:9999/api/';

export const elasticsearchHost = 'http://localhost:9200';
export const elasticsearchIndex = 'inventoryitems';

export const restfulAPIPatternsURL = apiBaseUrl + 'autogenerated/api/patterns.json'

export const swaggerUIURL = 'http://127.0.0.1:8080/#/';

export const registrationIsEnabled = true;

export const searchSortingConfig = [
  {label: 'Relevance', field: '_score', order: 'desc'},
  {
    label: 'Title - Ascending',
    field: 'title.keyword',
    order: 'asc',
  },
  {
    label: 'Title - Descending',
    field: 'title.keyword',
    order: 'desc',
  },
  {
    label: 'Description - Ascending',
    field: 'description.keyword',
    order: 'asc',
  },
  {
    label: 'Description - Descending',
    field: 'description.keyword',
    order: 'desc',
  }
];


export const jsonSchemaUiSchema = {
  "ui:order": ["category", "title","isPublic","description","tags","*"],
  "inventoryItems":{
    "ui:options": {
      "addable": false,
      "orderable": false,
      "removable": false
    },
    "items":{
      "ui:order": ["category", "title","isPublic","description","tags","*"],

      "tags":{
        "ui:options": {
          "addable": false,
          "orderable": false,
          "removable": false
        }
      }
    }
  }
}