/* tslint:disable */
/* eslint-disable */
/**
 * Web2py marketplace demo
 * Web2py marketplace demo
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mark@myire.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

